import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import GlobalProviders from "@/components/GlobalProviders";

export const metadata: Metadata = {
  title: "AI合同审查",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <GlobalProviders>
          {children}
        </GlobalProviders>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}