// Code generated by tracegen. DO NOT EDIT.

package cache

import (
	"context"
	"time"

	"gitlab.internal.ops.haiyiai.tech/seaart-web-server/seago/utils/su_ytrace"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

const (
	tracedRdsTracerName = "seago/utils/cache"
)

// TracedRds Rds 接口的追踪代理
// Component: cache, SpanKind: client
type TracedRds struct {
	underlying Rds
	tracer     trace.Tracer
}

// NewTracedRds 创建追踪代理
func NewTracedRds(underlying Rds) *TracedRds {
	return &TracedRds{
		underlying: underlying,
	}
}

// getTracer 获取 tracer（延迟获取，确保追踪系统已初始化）
func (t *TracedRds) getTracer() trace.Tracer {
	return otel.Tracer(tracedRdsTracerName)
}


// Lock 追踪代理方法
func (t *TracedRds) Lock(ctx context.Context, k string, v string, ttl time.Duration) (bool, error) {
	// 检查追踪是否启用
	if !su_ytrace.IsEnabled() {
		// 追踪未启用，直接调用底层方法
		return t.underlying.Lock(ctx, k, v, ttl)
	}

	tracer := t.getTracer()

	// 提取 span（支持 Worker 和 Fiber 服务）
	ctx = su_ytrace.ExtractSpanFromContext(ctx)
	ctx, span := tracer.Start(ctx, "cache.Lock",
		trace.WithSpanKind(trace.SpanKindClient),
	)
	defer su_ytrace.SafeEndSpan(span)
	su_ytrace.MaybeSetRequestID(ctx, span)

	span.SetAttributes(
		attribute.String("cache.system", "cache"),
		attribute.String("cache.operation", "Lock"),
		attribute.String("cache.key", k),
		attribute.Int("cache.value.length", len(v)),
		attribute.String("cache.ttl", ttl.String()),
	)
	

	ret0, ret1 := t.underlying.Lock(ctx, k, v, ttl)

	
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	} else {
		span.SetStatus(codes.Ok, "")
	}
	

	return ret0, ret1
}

// Unlock 追踪代理方法
func (t *TracedRds) Unlock(ctx context.Context, k string, ranVal string) (bool, error) {
	// 检查追踪是否启用
	if !su_ytrace.IsEnabled() {
		// 追踪未启用，直接调用底层方法
		return t.underlying.Unlock(ctx, k, ranVal)
	}

	tracer := t.getTracer()

	// 提取 span（支持 Worker 和 Fiber 服务）
	ctx = su_ytrace.ExtractSpanFromContext(ctx)
	ctx, span := tracer.Start(ctx, "cache.Unlock",
		trace.WithSpanKind(trace.SpanKindClient),
	)
	defer su_ytrace.SafeEndSpan(span)
	su_ytrace.MaybeSetRequestID(ctx, span)

	span.SetAttributes(
		attribute.String("cache.system", "cache"),
		attribute.String("cache.operation", "Unlock"),
		attribute.String("cache.key", k),
	)
	

	ret0, ret1 := t.underlying.Unlock(ctx, k, ranVal)

	
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	} else {
		span.SetStatus(codes.Ok, "")
	}
	

	return ret0, ret1
}

// Client 追踪代理方法
func (t *TracedRds) Client() (Client) {
	

	ret0 := t.underlying.Client()

	

	return ret0
}

// Close 追踪代理方法
func (t *TracedRds) Close() (error) {
	

	ret0 := t.underlying.Close()

	

	return ret0
}

// PipeExec 追踪代理方法
func (t *TracedRds) PipeExec(ctx context.Context, fn PipeExecHandler) (error) {
	// 检查追踪是否启用
	if !su_ytrace.IsEnabled() {
		// 追踪未启用，直接调用底层方法
		return t.underlying.PipeExec(ctx, fn)
	}

	tracer := t.getTracer()

	// 提取 span（支持 Worker 和 Fiber 服务）
	ctx = su_ytrace.ExtractSpanFromContext(ctx)
	ctx, span := tracer.Start(ctx, "cache.PipeExec",
		trace.WithSpanKind(trace.SpanKindClient),
	)
	defer su_ytrace.SafeEndSpan(span)
	su_ytrace.MaybeSetRequestID(ctx, span)

	span.SetAttributes(
		attribute.String("cache.system", "cache"),
		attribute.String("cache.operation", "PipeExec"),
	)
	

	ret0 := t.underlying.PipeExec(ctx, fn)

	
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	} else {
		span.SetStatus(codes.Ok, "")
	}
	

	return ret0
}

